### ISSUE TITLE
[Meta-Issue] Change all links in FOSSASIA subdomains to match the correct page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#294]
Change all links across FOSSASIA subdomains and ensure the following links are working
* [ ] sitemap.html -> sitemap/index.html
* [ ] licenses.html -> licenses/index.html
* [ ] about.html -> /about/index.html
* [ ] apply.html -> /apply/index.html
* [ ] team.html -> /team/index.html
* [ ] thankyou.html -> /thankyou/index.html
* [ ] mailthanks.html -> /mailthanks/index.html
* [ ] donate.html -> /donate/index.html

e.g. on subdomains: coc.fossasia.org, labs.fossasia.org, events.fossasia.org etc.

**Comment by yashLadha** [comment]
Claiming the issue @mariobehling

**Comment by mariobehling** [comment]
This issue needs to be solved in multiple repositories.

**Comment by BolajiAyodeji** [comment]
Working on this @mariobehling 
which of the directories are fixed already?
